jets:
  inputs:
    - absEta
    - pt
    - "ditau_idx"
    - "ditau_phi"
    - "ditau_e"
    - "ditau_BDTScore"
    - "ditau_E_frac_subl"
    - "ditau_E_frac_subsubl"
    - "ditau_IsTruthHadronic"
    - "ditau_IsTruthMatched"
    - "ditau_R_core"
    - "ditau_R_core_lead"
    - "ditau_R_core_subl"
    - "ditau_R_isotrack"
    - "ditau_R_max_lead"
    - "ditau_R_max_subl"
    - "ditau_R_subjet"
    - "ditau_R_subjets_subl"
    - "ditau_R_subjets_subsubl"
    - "ditau_R_track"
    - "ditau_R_track_all"
    - "ditau_R_track_core"
    - "ditau_R_tracks_lead"
    - "ditau_R_tracks_subl"
    - "ditau_TauJetVtxFraction"
    - "ditau_d0_leadtrack_lead"
    - "ditau_d0_leadtrack_subl"
    - "ditau_ditau_pt"
    - "ditau_f_isotracks"
    - "ditau_f_subjet_lead"
    - "ditau_f_subjet_subl"
    - "ditau_f_subjets"
    - "ditau_f_track_lead"
    - "ditau_f_track_subl"
    - "ditau_m"
    - "ditau_m_core_lead"
    - "ditau_m_core_subl"
    - "ditau_m_track"
    - "ditau_m_track_all"
    - "ditau_m_track_core"
    - "ditau_m_tracks_lead"
    - "ditau_m_tracks_subl"
    - "ditau_n_iso_ellipse"
    - "ditau_n_isotrack"
    - "ditau_n_subjets"
    - "ditau_n_track"
    - "ditau_n_tracks_lead"
    - "ditau_n_tracks_subl"
  labels:
    - HadronConeExclTruthLabelID
tracks:
  inputs:
    - "TruthType"
    - "d0TJVA"
    - "z0TJVA"
    - "trkType"
    - "charge"
    - "truthParticleOrigin"
    - "trackPt"
    - "trackEta"
    - "trackPhi"
    - "numberOfInnermostPixelLayerHits"
    - "numberOfPixelHits"
    - "numberOfPixelSharedHits"
    - "numberOfPixelDeadSensors"
    - "numberOfSCTHits"
    - "numberOfSCTSharedHits"
    - "numberOfSCTDeadSensors"
    - "numberOfTRTHighThresholdHits"
    - "numberOfTRTHits"
    - "expectInnermostPixelLayerHit"
    - "expectNextToInnermostPixelLayerHit"
    - "numberOfContribPixelLayers"
    - "numberOfPixelHoles"
    - "numberOfSCTHoles"
    - "qOverP"
    - "theta"
    - "eProbabilityHT"
    - "eProbabilityNN"
    - "eProbabilityNNorHT"
    - "pixeldEdx"
    - "dtIdx"
  # labels:
  #   - tauTruthProng
  #   - tauTruthDecayMode
  #   - NewTruthType

subjets:
  inputs:
    - "ditau_subjet_pt"
    - "ditau_subjet_eta"
    - "ditau_subjet_phi"
    - "ditau_subjet_e"
    - "ditau_n_tracks"
  # labels:
  #   - HadronConeExclTruthLabelID
