muons:
  inputs:
    - pt_track
    - eta_track
    - phi_track
    - ptvarcone30TTVARel
    - topoetcone30Rel
    - ptfrac_track
    - ptrel_track
    - dRtrackjet_track
    - nTracksTrackjet
  labels:
    - iffClass
    - muonType
    - pt
    - eta
    - phi

muon_tracks:
  inputs:
    - ptfrac
    - dr_trackjet
    - dr_muon
    - btagIp_d0
    - btagIp_z0SinTheta
    - btagIp_d0Uncertainty
    - btagIp_z0SinTheta
    - btagIp_d0_significance
    - numberOfPixelHits
    - numberOfInnermostPixelLayerHits
    - numberOfNextToInnermostPixelLayerHits
    - numberOfInnermostPixelLayerSharedHits
    - numberOfInnermostPixelLayerSplitHits
    - numberOfPixelSharedHits
    - numberOfPixelSplitHits
    - numberOfSCTHits
    - numberOfSCTSharedHits
  labels:
    - ftagTruthOriginLabel
    - ftagTruthTypeLabel
    - ftagTruthVertexIndex

#flow:
#  inputs:
#    - pt
#    - energy
#    - deta
#    - dphi
