variables: !include plit_electron_variables.yaml
#transform: !include transform.yaml

ttbar: &ttbar
  name: ttbar
  equal_jets: False
  pattern:
    - "user.pgadow.LD_2023_12_07.601589.PhPy8EG_A14_ttbar_hdamp258p75_nonallhadron.e8547_s3797_r13144_p5934_TREE/*.h5"
    - "user.pgadow.LD_2023_12_07.601589.PhPy8EG_A14_ttbar_hdamp258p75_nonallhadron.e8549_s4159_r14799_p5934_TREE/*.h5"
    - "user.pgadow.LD_2023_12_07.601589.PhPy8EG_A14_ttbar_hdamp258p75_nonallhadron.e8549_s4162_r14622_p5934_TREE/*.h5"

global_cuts:
  train:
    - [eventNumber, "%10<=", 7]
  val:
    - [eventNumber, "%10==", 8]
  test:
    - [eventNumber, "%10==", 9]

electron: &electron
  name: electron
  cuts:
    - [pt, ">", 10_000]

components:
  - region:
      <<: *electron
    sample:
      <<: *ttbar
    flavours: [elxprompt]
    num_jets: 4_000_000

  - region:
      <<: *electron
    sample:
      <<: *ttbar
    flavours: [npxall]
    num_jets: 1_000_000


resampling:
  target: elxprompt
  method: countup
  sampling_fraction: 1.0
  variables:
    pt:
      bins: [[10_000, 50_000, 8], [50_000, 100_000, 5], [100_000, 500_000, 20], [500_000, 1_000_000, 5]]
    eta:
      bins: [[-2.47, -1.52, 8], [-1.37, 1.37, 22],[1.52, 2.47, 8]]

# note: sensible defaults are defined in the PreprocessingConfig constructor
global:
  jets_name: electrons
  batch_size: 1_000_000
  num_jets_estimate: 5_000
  base_dir: /data/pgadow/atlas/plit/preprocessed/electrons_5M
  ntuple_dir: /data/pgadow/atlas/plit/ntuples
  out_dir: /data/pgadow/atlas/plit/preprocessed/electrons_5M
