variables: !include plit_electron_variables.yaml
#transform: !include transform.yaml

ttbar: &ttbar
  name: ttbar
  equal_jets: False
  pattern:
    - "user.pgadow.LD_2023_12_20.410471.PhPy8EG_A14_ttbar_hdamp258p75_allhad.e6337_s3681_r13144_p5934_TREE/*.h5"
    - "user.pgadow.LD_2023_12_20.601237.PhPy8EG_A14_ttbar_hdamp258p75_allhad.e8514_s4111_r14622_p5934_TREE/*.h5"
    - "user.pgadow.LD_2023_12_20.601589.PhPy8EG_A14_ttbar_hdamp258p75_nonallhadron.e8547_s3797_r13144_p5934_TREE/*.h5"
    - "user.pgadow.LD_2023_12_20.601589.PhPy8EG_A14_ttbar_hdamp258p75_nonallhadron.e8549_s4159_r14799_p5934_TREE/*.h5"
    - "user.pgadow.LD_2023_12_20.601589.PhPy8EG_A14_ttbar_hdamp258p75_nonallhadron.e8549_s4162_r14622_p5934_TREE/*.h5"

zprime: &zprime
  name: zprime
  equal_jets: False
  pattern:
    - "user.pgadow.LD_2023_12_20.800030.Py8EG_A14NNPDF23LO_flatpT_Zprime_Extended.e7954_s3681_r13144_p5934_TREE/*.h5"
    - "user.pgadow.LD_2023_12_20.800030.Py8EG_A14NNPDF23LO_flatpT_Zprime_Extended.e8514_s4162_r14622_p5934_TREE/*.h5"

global_cuts:
  train:
    - [eventNumber, "%10<=", 7]
  val:
    - [eventNumber, "%10==", 8]
  test:
    - [eventNumber, "%10==", 9]

lowpt: &lowpt
  name: lowpt
  cuts:
    - [pt, ">", 10_000]
    - [absEta, "<", 1.37]

highpt: &highpt
  name: highpt
  cuts:
    - [pt, ">", 100_000]
    - [absEta, "<", 1.37]

components:
  - region:
      <<: *lowpt
    sample:
      <<: *ttbar
    flavours: [elxprompt]
    num_jets: 8_800_000

  - region:
      <<: *lowpt
    sample:
      <<: *ttbar
    flavours: [npxall]
    num_jets: 2_200_000

  - region:
      <<: *highpt
    sample:
      <<: *zprime
    flavours: [elxprompt]
    num_jets: 1_200_000

  - region:
      <<: *highpt
    sample:
      <<: *zprime
    flavours: [npxall]
    num_jets: 300_000

resampling:
  target: elxprompt
  method: countup
  sampling_fraction: 1.0
  variables:
    pt:
      bins: [[10_000, 50_000, 8], [50_000, 100_000, 5], [100_000, 500_000, 5], [500_000, 2_000_000, 3]]
    eta:
      bins: [[-1.37, 1.37, 22]]
# note: sensible defaults are defined in the PreprocessingConfig constructor
global:
  jets_name: electrons
  batch_size: 1_000_000
  num_jets_estimate: 2_000_000
  base_dir: /data/pgadow/atlas/plit/preprocessed/electrons_hybrid_barrel
  ntuple_dir: /data/pgadow/atlas/plit/ntuples
  out_dir: /data/pgadow/atlas/plit/preprocessed/electrons_hybrid_barrel
