variables: !include variables.yaml
#transform: !include transform.yaml

ttbar: &ttbar
  name: ttbar
  pattern: "*.410470.e6337_s3681_r13144_p5169.tdd.*.h5/*.h5"
zprime: &zprime
  name: zprime
  pattern: "*.800030.e7954_s3681_r13144_p5169.tdd.*.h5/*.h5"

global_cuts:
  train:
    - [eventNumber, "%10<=", 7]
  val:
    - [eventNumber, "%10==", 8]
  test:
    - [eventNumber, "%10==", 9]

lowpt: &lowpt
  name: lowpt
  cuts:
    - [pt_btagJes, ">", 20_000]
    - [pt_btagJes, "<", 250_000]
highpt: &highpt
  name: highpt
  cuts:
    - [pt_btagJes, ">", 250_000]
    - [pt_btagJes, "<", 6_000_000]

components:
  - region:
      <<: *lowpt
    sample:
      <<: *ttbar
    flavours: [cjets]
    num_jets: 40_000_000

  - region:
      <<: *lowpt
    sample:
      <<: *ttbar
    flavours: [bjets, ujets]
    num_jets: 70_000_000

  - region:
      <<: *highpt
    sample:
      <<: *zprime
    flavours: [bjets, cjets]
    num_jets: 9_000_000

  - region:
      <<: *highpt
    sample:
      <<: *zprime
    flavours: [ujets]
    num_jets: 15_000_000

resampling:
  target: cjets
  method: countup
  sampling_fraction: auto
  variables:
    pt_btagJes:
      bins: [[20_000, 250_000, 50], [250_000, 1_000_000, 50], [1_000_000, 6_000_000, 50]]
    absEta_btagJes:
      bins: [[0, 2.5, 20]]

# note: sensible defaults are defined in the PreprocessingConfig constructor
global:
  jets_name: jets
  batch_size: 1_000_000
  num_jets_estimate: 5_000_000
  base_dir: /unix/atlastracking/svanstroud/seminar/samples/

