variables: !include variables.yaml

ttbar: &ttbar
  name: ttbar
  equal_jets: False
  pattern:
    - "user.svanstro.410470.e6337_s3681_r13144_p5922.tdd.EMPFlow_kfold.24_2_27.23-11-10_kfoldtrain_output.h5/*.h5"
    - "user.svanstro.601229.e8514_s4162_r14622_p5922.tdd.EMPFlow_kfold.24_2_27.23-11-10_kfoldtrain_output.h5/*.h5"
    - "user.svanstro.601230.e8514_s4162_r14622_p5922.tdd.EMPFlow_kfold.24_2_27.23-11-10_kfoldtrain_output.h5/*.h5"

zprime: &zprime
  name: zprime
  equal_jets: False
  pattern:
    - "user.svanstro.800030.e7954_s3681_r13144_p5922.tdd.EMPFlow_kfold.24_2_27.23-11-10_kfoldtrain_output.h5/*.h5"
    - "user.svanstro.800030.e7954_s3797_r13144_p5922.tdd.EMPFlow_kfold.24_2_27.23-11-19_kfoldtrain_output.h5/*.h5"
    - "user.svanstro.800030.e8514_s4162_r14622_p5922.tdd.EMPFlow_kfold.24_2_27.23-11-10_kfoldtrain_output.h5/*.h5"

global_cuts:
  train:
    - [jetFoldHash, "%4!=", 0] # uncomment to run fold 0
    # - [jetFoldHash, "%4!=", 1] # uncomment to run fold 1
    # - [jetFoldHash, "%4!=", 2] # uncomment to run fold 2
    # - [jetFoldHash, "%4!=", 3] # uncomment to run fold 3
    - [eventNumber, "%10<=", 8]
  val:
    - [jetFoldHash, "%4!=", 0] # uncomment to run fold 0
    # - [jetFoldHash, "%4!=", 1] # uncomment to run fold 1
    # - [jetFoldHash, "%4!=", 2] # uncomment to run fold 2
    # - [jetFoldHash, "%4!=", 3] # uncomment to run fold 3
    - [eventNumber, "%10==", 9]
  test:
    - [jetFoldHash, "%4==", 0] # uncomment to run fold 0
    # - [jetFoldHash, "%4==", 1] # uncomment to run fold 1
    # - [jetFoldHash, "%4==", 2] # uncomment to run fold 2
    # - [jetFoldHash, "%4==", 3] # uncomment to run fold 3

lowpt: &lowpt
  name: lowpt
  cuts:
    - [pt_btagJes, ">", 20_000]
    - [pt_btagJes, "<", 250_000]
highpt: &highpt
  name: highpt
  cuts:
    - [pt_btagJes, ">", 250_000]
    - [pt_btagJes, "<", 6_000_000]

components:
  - region:
      <<: *lowpt
    sample:
      <<: *ttbar
    flavours: [bjets, cjets]
    num_jets: 45_000_000
    equal_jets: False

  - region:
      <<: *lowpt
    sample:
      <<: *ttbar
    flavours: [ujets]
    num_jets: 90_000_000
    equal_jets: False

  - region:
      <<: *lowpt
    sample:
      <<: *ttbar
    flavours: [taujets]
    num_jets: 6_250_000
    equal_jets: False

  - region:
      <<: *highpt
    sample:
      <<: *zprime
    flavours: [bjets, cjets]
    num_jets: 18_000_000
    equal_jets: False

  - region:
      <<: *highpt
    sample:
      <<: *zprime
    flavours: [ujets]
    num_jets: 36_000_000
    equal_jets: False

  - region:
      <<: *highpt
    sample:
      <<: *zprime
    flavours: [taujets]
    num_jets: 2_500_000
    equal_jets: False


resampling:
  target: cjets
  method: countup
  sampling_fraction: auto
  variables:
    pt_btagJes:
      bins: [[20_000, 250_000, 50], [250_000, 1_000_000, 50], [1_000_000, 6_000_000, 50]]
    absEta_btagJes:
      bins: [[0, 2.5, 20]]

# note: sensible defaults are defined in the PreprocessingConfig constructor
global:
  jets_name: jets
  batch_size: 1_000_000
  num_jets_estimate: 25_000_000
  base_dir: /home/xzcappon/phd/datasets/combined_run2_run3/p5922/high_stats/fold0
  ntuple_dir: /home/xucapsva/data/ftag/h5/gn2_v01/ntuples
