jets:
  inputs:
    - absEta
    - pt
    - TauJets.centFrac
    - TauJets.sumEMCellEtOverLeadTrkPt
    - TauJets.dRmax
    - TauJets.trFlightPathSig
    - TauJets.etOverPtLeadTrk
    - TauJets.ptRatioEflowApprox
    - TauJets.mEflowApprox
    - TauJets.massTrkSys
    - TauJets.SumPtTrkFrac
    - TauJets.EMPOverTrkSysP
    - TauJets.isolFrac
    - "TauJets.GNTauProbTau"
    - "TauJets.GNTauProbJet"
    - "TauJets.GNTauScore"
  labels:
    - HadronConeExclTruthLabelID

tracks:
  inputs:
    - TauTracks.dEtaJetSeedAxis
    - TauTracks.dPhiJetSeedAxis
    - TauTracks.trackPt
    - TauTracks.trackEta
    - TauTracks.trackPhi
    - TauTracks.numberOfInnermostPixelLayerHits
    - TauTracks.numberOfPixelHits
    - TauTracks.numberOfPixelSharedHits
    - TauTracks.numberOfPixelDeadSensors
    - TauTracks.numberOfSCTHits
    - TauTracks.numberOfSCTSharedHits
    - TauTracks.numberOfSCTDeadSensors
    - TauTracks.numberOfTRTHighThresholdHits
    - TauTracks.numberOfTRTHits
    - TauTracks.nPixHits
    - TauTracks.nSCTHits
    - TauTracks.nSiHits
    - TauTracks.nIBLHitsAndExp
    - TauTracks.expectInnermostPixelLayerHit
    - TauTracks.expectNextToInnermostPixelLayerHit
    - TauTracks.numberOfContribPixelLayers
    - TauTracks.numberOfPixelHoles
    - TauTracks.d0_old
    - TauTracks.qOverP
    - TauTracks.theta
    - TauTracks.z0sinthetaSigTJVA
    - TauTracks.z0sinthetaTJVA
    - TauTracks.d0SigTJVA
    - TauTracks.d0TJVA
    - TauTracks.z0TJVA
    - TauTracks.dz0_TV_PV0
    - TauTracks.log_sumpt_TV
    - TauTracks.log_sumpt2_TV
    - TauTracks.log_sumpt_PV0
    - TauTracks.log_sumpt2_PV0
    - TauTracks.rConv
    - TauTracks.rConvII
    - TauTracks.charge
    - "TauTracks.rnn_chargedScore"
    - "TauTracks.rnn_isolationScore"
    - "TauTracks.rnn_conversionScore"
    - "TauTracks.rnn_fakeScore"
  labels:
    - TauJets.tauTruthProng
    - TauJets.tauTruthDecayMode
    - TauTracks.NewTruthType

cells:
  inputs:
    - TauClusters.cls_e
    - TauClusters.cls_et
    - TauClusters.cls_dPhi
    - TauClusters.cls_dEta
    - TauClusters.cls_SECOND_R
    - TauClusters.cls_SECOND_LAMBDA
    - TauClusters.cls_FIRST_ENG_DENS
    - TauClusters.cls_EM_PROBABILITY
    - TauClusters.cls_CENTER_MAG
    - TauClusters.cls_CENTER_LAMBDA
  # labels:
  #   - HadronConeExclTruthLabelID
#flow:
#  inputs:
#    - pt
#    - energy
#    - deta
#    - dphi
