variables: !include tau-variables.yaml

qcd: &qcd
  name: qcd
  pattern: "qcd/jet_samp*.h5"

tau: &tau
  name: tau
  pattern: "tau/tau_samp*.h5"

global_cuts:
  train:
    - [eventNumber, "%10<=", 0]
  val:
    - [eventNumber, "%10==", 0]
  test:
    - [eventNumber, "%10>=", 0]

lowpt: &lowpt
  name: lowpt
  cuts:
    []
    # - [pt, ">=", 20_000]
    # - [pt, "<=", 150_000]

components:
  - region:
      <<: *lowpt
    sample:
      <<: *qcd
    flavours: [ujets]
    num_jets: 1
    # num_jets_val: 7_400_000
    num_jets_test: 500

  - region:
      <<: *lowpt
    sample:
      <<: *tau
    flavours: [bjets]
    num_jets: 1
    # num_jets_val: 1_600_000
    num_jets_test: 500

resampling:
  target: bjets
  method: none
  sampling_fraction: None
  variables:
    pt:
      bins: [[5_000, 3_000_000,30]]
    absEta:
      bins: [[0, 2.5, 20]]

# note: sensible defaults are defined in the PreprocessingConfig constructor
global:
  jets_name: jets
  batch_size: 1000
  num_jets_estimate: 1000
  base_dir: /afs/cern.ch/work/n/ntamir/private/GNTau_Project/
  merge_test_samples: True
